# Eureka3 配置文件
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/ #向其他两个微服务注册
    register-with-eureka: false #不显示在Eureka
spring:
  application:
    name: eureka3
server:
  port: 8763
