# Eureka1
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/ #向其他两个微服务注册
#    register-with-eureka: false #不显示在注册中心
spring:
  application:
    name: eureka
server:
  port: 8761
