spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MrXuan3168/Spring-Cloud-Config-Repo.git   #git仓库地址，这里存的是各个微服务的配置文件
          username: 1004108488@qq.com
          # password: xxx  #配置仓库如果是公开的，可以不输入密码
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/  #向注册中心注册
server:
  port: 8090